name: Daily Stock Report

on:
  schedule:
    # UTC 기준입니다. 한국 시간 오전 8시는 UTC 23시입니다.
    - cron: '40 00 * * *' 
  workflow_dispatch: # 직접 버튼 눌러서 실행하고 싶을 때 사용

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 도구 설치
        run: pip install -r requirements.txt

      - name: 코드 실행
        # 바로 이 env 부분이 깃허브 금고에서 열쇠를 꺼내 파이썬 환경으로 넘겨주는 역할입니다.
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
